version: '3.9'
services:
  nl-query:
    build: .
    container_name: nl-query
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=sk-xxx # ou use .env
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
